server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 172.26.192.199
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: E:/Code/javaproject/leyou_store/leyou/ly-auth/ly-auth-service/src/main/resources/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称